In [2]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [3]:
#Load the dataset
import pandas as pd
df = pd.read_csv("gas_turbines.csv")
df.head()

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,114.70,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,114.72,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,114.71,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,114.72,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,114.72,10.612,3.2484,82.311

In [4]:
#Droping the column
X = df.drop(df.columns[7],axis = 1)
X

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,10.612,3.2484,82.311
...,...,...,...,...,...,...,...,...,...,...
15034,9.0301,1005.6,98.460,3.5421,19.164,1049.7,546.21,10.400,4.5186,79.559
15035,7.8879,1005.9,99.093,3.5059,19.414,1046.3,543.22,10.433,4.8470,79.917
15036,7.2647,1006.3,99.496,3.4770,19.530,1037.7,537.32,10.483,7.9632,90.912
15037,7.0060,1006.8,99.008,3.4486,19.377,1043.2,541.24,10.533,6.2494,93.227
15038,6.9279,1007.2,97.533,3.4275,19.306,1049.9,545.85,10.583,4.9816,92.498

In [5]:
#Dependent Variable
Y = df['TEY']

In [6]:
#Data Modeling
model = Sequential()
model.add(Dense(12, input_dim=10,  activation='relu')) #input layer
model.add(Dense(1, activation='linear')) #output layer

In [7]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_squared_error'])

In [8]:
history = model.fit(X, Y, validation_split=0.33, epochs=50, batch_size=10)

Epoch 1/50
1008/1008 [==============================] - 3s 2ms/step - loss: 466.6704 - mean_squared_error: 466.6704 - val_loss: 181.9385 - val_mean_squared_error: 181.9385
Epoch 2/50
1008/1008 [==============================] - 2s 2ms/step - loss: 128.2156 - mean_squared_error: 128.2156 - val_loss: 113.3085 - val_mean_squared_error: 113.3085
Epoch 3/50
1008/1008 [==============================] - 2s 2ms/step - loss: 62.9043 - mean_squared_error: 62.9043 - val_loss: 84.0019 - val_mean_squared_error: 84.0019
Epoch 4/50
1008/1008 [==============================] - 3s 3ms/step - loss: 36.1138 - mean_squared_error: 36.1138 - val_loss: 31.4800 - val_mean_squared_error: 31.4800
Epoch 5/50
1008/1008 [==============================] - 2s 2ms/step - loss: 22.9391 - mean_squared_error: 22.9391 - val_loss: 21.4817 - val_mean_squared_error: 21.4817
Epoch 6/50
1008/1008 [==============================] - 2s 2ms/step - loss: 13.4833 - mean_squared_error: 13.4833 - val_loss: 19.4332 - val_mean_squared_error: 19.4332
Epoch 7/50
1008/1008 [==============================] - 2s 2ms/step - loss: 8.6050 - mean_squared_error: 8.6050 - val_loss: 7.0309 - val_mean_squared_error: 7.0309
Epoch 8/50
1008/1008 [==============================] - 2s 2ms/step - loss: 5.1782 - mean_squared_error: 5.1782 - val_loss: 3.2879 - val_mean_squared_error: 3.2879
Epoch 9/50
1008/1008 [==============================] - 2s 2ms/step - loss: 3.8010 - mean_squared_error: 3.8010 - val_loss: 2.6362 - val_mean_squared_error: 2.6362
Epoch 10/50
1008/1008 [==============================] - 3s 3ms/step - loss: 3.3863 - mean_squared_error: 3.3863 - val_loss: 6.1622 - val_mean_squared_error: 6.1622
Epoch 11/50
1008/1008 [==============================] - 2s 2ms/step - loss: 3.0719 - mean_squared_error: 3.0719 - val_loss: 1.6280 - val_mean_squared_error: 1.6280
Epoch 12/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.8636 - mean_squared_error: 2.8636 - val_loss: 1.7059 - val_mean_squared_error: 1.7059
Epoch 13/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.6123 - mean_squared_error: 2.6123 - val_loss: 3.2047 - val_mean_squared_error: 3.2047
Epoch 14/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.4942 - mean_squared_error: 2.4942 - val_loss: 5.4401 - val_mean_squared_error: 5.4401
Epoch 15/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.4847 - mean_squared_error: 2.4847 - val_loss: 1.7533 - val_mean_squared_error: 1.7533
Epoch 16/50
1008/1008 [==============================] - 3s 2ms/step - loss: 2.1542 - mean_squared_error: 2.1542 - val_loss: 1.8769 - val_mean_squared_error: 1.8769
Epoch 17/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.1996 - mean_squared_error: 2.1996 - val_loss: 4.4076 - val_mean_squared_error: 4.4076
Epoch 18/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.2719 - mean_squared_error: 2.2719 - val_loss: 2.2401 - val_mean_squared_error: 2.2401
Epoch 19/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.1197 - mean_squared_error: 2.1197 - val_loss: 3.9379 - val_mean_squared_error: 3.9379
Epoch 20/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.1605 - mean_squared_error: 2.1605 - val_loss: 1.3828 - val_mean_squared_error: 1.3828
Epoch 21/50
1008/1008 [==============================] - 3s 3ms/step - loss: 2.2094 - mean_squared_error: 2.2094 - val_loss: 1.4637 - val_mean_squared_error: 1.4637
Epoch 22/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.1256 - mean_squared_error: 2.1256 - val_loss: 1.3684 - val_mean_squared_error: 1.3684
Epoch 23/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0126 - mean_squared_error: 2.0126 - val_loss: 1.2550 - val_mean_squared_error: 1.2550
Epoch 24/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0261 - mean_squared_error: 2.0261 - val_loss: 1.2934 - val_mean_squared_error: 1.2934
Epoch 25/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.1698 - mean_squared_error: 2.1698 - val_loss: 1.7553 - val_mean_squared_error: 1.7553
Epoch 26/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8935 - mean_squared_error: 1.8935 - val_loss: 1.4868 - val_mean_squared_error: 1.4868
Epoch 27/50
1008/1008 [==============================] - 3s 3ms/step - loss: 1.9803 - mean_squared_error: 1.9803 - val_loss: 1.8861 - val_mean_squared_error: 1.8861
Epoch 28/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.2117 - mean_squared_error: 2.2117 - val_loss: 1.3437 - val_mean_squared_error: 1.3437
Epoch 29/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.9606 - mean_squared_error: 1.9606 - val_loss: 1.4447 - val_mean_squared_error: 1.4447
Epoch 30/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.9336 - mean_squared_error: 1.9336 - val_loss: 1.7062 - val_mean_squared_error: 1.7062
Epoch 31/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0657 - mean_squared_error: 2.0657 - val_loss: 1.3423 - val_mean_squared_error: 1.3423
Epoch 32/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0919 - mean_squared_error: 2.0919 - val_loss: 4.3317 - val_mean_squared_error: 4.3317
Epoch 33/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0736 - mean_squared_error: 2.0736 - val_loss: 1.3060 - val_mean_squared_error: 1.3060
Epoch 34/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0343 - mean_squared_error: 2.0343 - val_loss: 2.8984 - val_mean_squared_error: 2.8984
Epoch 35/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8586 - mean_squared_error: 1.8586 - val_loss: 1.2968 - val_mean_squared_error: 1.2968
Epoch 36/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8928 - mean_squared_error: 1.8928 - val_loss: 2.3990 - val_mean_squared_error: 2.3990
Epoch 37/50
1008/1008 [==============================] - 2s 2ms/step - loss: 2.0599 - mean_squared_error: 2.0599 - val_loss: 1.5963 - val_mean_squared_error: 1.5963
Epoch 38/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.9257 - mean_squared_error: 1.9257 - val_loss: 1.7135 - val_mean_squared_error: 1.7135
Epoch 39/50
1008/1008 [==============================] - 3s 3ms/step - loss: 2.0110 - mean_squared_error: 2.0110 - val_loss: 1.2788 - val_mean_squared_error: 1.2788
Epoch 40/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8804 - mean_squared_error: 1.8804 - val_loss: 2.4234 - val_mean_squared_error: 2.4234
Epoch 41/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.9015 - mean_squared_error: 1.9015 - val_loss: 1.4750 - val_mean_squared_error: 1.4750
Epoch 42/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8261 - mean_squared_error: 1.8261 - val_loss: 1.2942 - val_mean_squared_error: 1.2942
Epoch 43/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.9292 - mean_squared_error: 1.9292 - val_loss: 1.6437 - val_mean_squared_error: 1.6437
Epoch 44/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.7808 - mean_squared_error: 1.7808 - val_loss: 1.5124 - val_mean_squared_error: 1.5124
Epoch 45/50
1008/1008 [==============================] - 3s 3ms/step - loss: 1.8708 - mean_squared_error: 1.8708 - val_loss: 1.3877 - val_mean_squared_error: 1.3877
Epoch 46/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.9051 - mean_squared_error: 1.9051 - val_loss: 1.3581 - val_mean_squared_error: 1.3581
Epoch 47/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8729 - mean_squared_error: 1.8729 - val_loss: 2.2562 - val_mean_squared_error: 2.2562
Epoch 48/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.8590 - mean_squared_error: 1.8590 - val_loss: 1.3115 - val_mean_squared_error: 1.3115
Epoch 49/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.7775 - mean_squared_error: 1.7775 - val_loss: 2.4567 - val_mean_squared_error: 2.4567
Epoch 50/50
1008/1008 [==============================] - 2s 2ms/step - loss: 1.7826 - mean_squared_error: 1.7826 - val_loss: 1.3157 - val_mean_squared_error: 1.3157